"""refactor_architecture_pivot_inscription

Revision ID: 1299f2bb0f74
Revises: b3e067d588b0
Create Date: 2026-03-12 16:45:47.371500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1299f2bb0f74'
down_revision: Union[str, Sequence[str], None] = 'b3e067d588b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annonces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('auteur_id', sa.UUID(), nullable=False),
    sa.Column('audience', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annonces_auteur_id'), 'annonces', ['auteur_id'], unique=False)
    op.create_index(op.f('ix_annonces_id'), 'annonces', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('lue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('responsables_pedagogiques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsables_pedagogiques_id'), 'responsables_pedagogiques', ['id'], unique=False)
    op.create_index(op.f('ix_responsables_pedagogiques_user_id'), 'responsables_pedagogiques', ['user_id'], unique=False)
    op.create_table('absences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eleve_id', sa.UUID(), nullable=False),
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('classe_id', sa.UUID(), nullable=False),
    sa.Column('annee_scolaire_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('justifiee', sa.Boolean(), nullable=True),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaires.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absences_annee_scolaire_id'), 'absences', ['annee_scolaire_id'], unique=False)
    op.create_index(op.f('ix_absences_classe_id'), 'absences', ['classe_id'], unique=False)
    op.create_index(op.f('ix_absences_eleve_id'), 'absences', ['eleve_id'], unique=False)
    op.create_index(op.f('ix_absences_formateur_id'), 'absences', ['formateur_id'], unique=False)
    op.create_index(op.f('ix_absences_id'), 'absences', ['id'], unique=False)
    op.create_table('cours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('matiere_id', sa.UUID(), nullable=False),
    sa.Column('classe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cours_classe_id'), 'cours', ['classe_id'], unique=False)
    op.create_index(op.f('ix_cours_formateur_id'), 'cours', ['formateur_id'], unique=False)
    op.create_index(op.f('ix_cours_id'), 'cours', ['id'], unique=False)
    op.create_index(op.f('ix_cours_matiere_id'), 'cours', ['matiere_id'], unique=False)
    op.create_table('emplois_du_temps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classe_id', sa.UUID(), nullable=False),
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('matiere_id', sa.UUID(), nullable=False),
    sa.Column('annee_scolaire_id', sa.UUID(), nullable=False),
    sa.Column('jour', sa.String(), nullable=False),
    sa.Column('heure_debut', sa.String(), nullable=False),
    sa.Column('heure_fin', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaires.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emplois_du_temps_annee_scolaire_id'), 'emplois_du_temps', ['annee_scolaire_id'], unique=False)
    op.create_index(op.f('ix_emplois_du_temps_classe_id'), 'emplois_du_temps', ['classe_id'], unique=False)
    op.create_index(op.f('ix_emplois_du_temps_formateur_id'), 'emplois_du_temps', ['formateur_id'], unique=False)
    op.create_index(op.f('ix_emplois_du_temps_id'), 'emplois_du_temps', ['id'], unique=False)
    op.create_index(op.f('ix_emplois_du_temps_matiere_id'), 'emplois_du_temps', ['matiere_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('matiere_id', sa.UUID(), nullable=False),
    sa.Column('classe_id', sa.UUID(), nullable=False),
    sa.Column('annee_scolaire_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('bareme', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaires.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_annee_scolaire_id'), 'evaluations', ['annee_scolaire_id'], unique=False)
    op.create_index(op.f('ix_evaluations_classe_id'), 'evaluations', ['classe_id'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_evaluations_matiere_id'), 'evaluations', ['matiere_id'], unique=False)
    op.create_table('inscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eleve_id', sa.UUID(), nullable=False),
    sa.Column('classe_id', sa.UUID(), nullable=True),
    sa.Column('annee_scolaire_id', sa.UUID(), nullable=False),
    sa.Column('is_ancien', sa.Boolean(), nullable=False),
    sa.Column('date_inscription', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['annee_scolaire_id'], ['annee_scolaires.id'], ),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eleve_id', 'annee_scolaire_id', name='uq_inscription_eleve_annee')
    )
    op.create_index(op.f('ix_inscriptions_annee_scolaire_id'), 'inscriptions', ['annee_scolaire_id'], unique=False)
    op.create_index(op.f('ix_inscriptions_classe_id'), 'inscriptions', ['classe_id'], unique=False)
    op.create_index(op.f('ix_inscriptions_eleve_id'), 'inscriptions', ['eleve_id'], unique=False)
    op.create_index(op.f('ix_inscriptions_id'), 'inscriptions', ['id'], unique=False)
    op.create_table('parent_eleve',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('eleve_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'eleve_id')
    )
    op.create_table('devoirs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('consigne', sa.Text(), nullable=True),
    sa.Column('cours_id', sa.UUID(), nullable=True),
    sa.Column('classe_id', sa.UUID(), nullable=False),
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('date_limite', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devoirs_classe_id'), 'devoirs', ['classe_id'], unique=False)
    op.create_index(op.f('ix_devoirs_cours_id'), 'devoirs', ['cours_id'], unique=False)
    op.create_index(op.f('ix_devoirs_formateur_id'), 'devoirs', ['formateur_id'], unique=False)
    op.create_index(op.f('ix_devoirs_id'), 'devoirs', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eleve_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_eleve_id'), 'notes', ['eleve_id'], unique=False)
    op.create_index(op.f('ix_notes_evaluation_id'), 'notes', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('supports_pedagogiques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cours_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cours_id'], ['cours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supports_pedagogiques_cours_id'), 'supports_pedagogiques', ['cours_id'], unique=False)
    op.create_index(op.f('ix_supports_pedagogiques_id'), 'supports_pedagogiques', ['id'], unique=False)
    op.create_table('soumissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('devoir_id', sa.UUID(), nullable=False),
    sa.Column('eleve_id', sa.UUID(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('note', sa.Float(), nullable=True),
    sa.Column('appreciation', sa.Text(), nullable=True),
    sa.Column('soumis_le', sa.DateTime(), nullable=True),
    sa.Column('corrige_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['devoir_id'], ['devoirs.id'], ),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soumissions_devoir_id'), 'soumissions', ['devoir_id'], unique=False)
    op.create_index(op.f('ix_soumissions_eleve_id'), 'soumissions', ['eleve_id'], unique=False)
    op.create_index(op.f('ix_soumissions_id'), 'soumissions', ['id'], unique=False)
    op.alter_column('administrateurs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('annee_scolaires', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('annee_scolaires', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('classes', sa.Column('annee_scolaire_id', sa.UUID(), nullable=False))
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_classes_annee_scolaire_id'), 'classes', ['annee_scolaire_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'annee_scolaires', ['annee_scolaire_id'], ['id'])
    op.drop_column('classes', 'effectif')
    op.alter_column('directeurs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('eleves', sa.Column('matricule', sa.String(), nullable=False))
    op.alter_column('eleves', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_eleves_class_id'), table_name='eleves')
    op.create_index(op.f('ix_eleves_matricule'), 'eleves', ['matricule'], unique=True)
    op.drop_constraint(op.f('eleves_class_id_fkey'), 'eleves', type_='foreignkey')
    op.drop_column('eleves', 'class_id')
    op.add_column('formateur_classe', sa.Column('annee_scolaire_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'formateur_classe', 'annee_scolaires', ['annee_scolaire_id'], ['id'])
    op.add_column('formateur_matiere', sa.Column('annee_scolaire_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'formateur_matiere', 'annee_scolaires', ['annee_scolaire_id'], ['id'])
    op.alter_column('formateurs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('matieres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_matieres_name'), table_name='matieres')
    op.create_index(op.f('ix_matieres_name'), 'matieres', ['name'], unique=True)
    op.alter_column('parents', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_parents_student_id'), table_name='parents')
    op.drop_constraint(op.f('parents_student_id_fkey'), 'parents', type_='foreignkey')
    op.drop_column('parents', 'student_id')
    op.alter_column('utilisateurs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('utilisateurs', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_utilisateurs_scholar_year_id'), table_name='utilisateurs')
    op.drop_constraint(op.f('utilisateurs_scholar_year_id_fkey'), 'utilisateurs', type_='foreignkey')
    op.drop_column('utilisateurs', 'scholar_year_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('scholar_year_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('utilisateurs_scholar_year_id_fkey'), 'utilisateurs', 'annee_scolaires', ['scholar_year_id'], ['id'])
    op.create_index(op.f('ix_utilisateurs_scholar_year_id'), 'utilisateurs', ['scholar_year_id'], unique=False)
    op.alter_column('utilisateurs', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('utilisateurs', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('utilisateurs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('parents', sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('parents_student_id_fkey'), 'parents', 'eleves', ['student_id'], ['id'])
    op.create_index(op.f('ix_parents_student_id'), 'parents', ['student_id'], unique=False)
    op.alter_column('parents', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_matieres_name'), table_name='matieres')
    op.create_index(op.f('ix_matieres_name'), 'matieres', ['name'], unique=False)
    op.alter_column('matieres', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('formateurs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'formateur_matiere', type_='foreignkey')
    op.drop_column('formateur_matiere', 'annee_scolaire_id')
    op.drop_constraint(None, 'formateur_classe', type_='foreignkey')
    op.drop_column('formateur_classe', 'annee_scolaire_id')
    op.add_column('eleves', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('eleves_class_id_fkey'), 'eleves', 'classes', ['class_id'], ['id'])
    op.drop_index(op.f('ix_eleves_matricule'), table_name='eleves')
    op.create_index(op.f('ix_eleves_class_id'), 'eleves', ['class_id'], unique=False)
    op.alter_column('eleves', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('eleves', 'matricule')
    op.alter_column('directeurs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('classes', sa.Column('effectif', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_annee_scolaire_id'), table_name='classes')
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('classes', 'annee_scolaire_id')
    op.alter_column('annee_scolaires', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('annee_scolaires', 'is_active')
    op.alter_column('administrateurs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_soumissions_id'), table_name='soumissions')
    op.drop_index(op.f('ix_soumissions_eleve_id'), table_name='soumissions')
    op.drop_index(op.f('ix_soumissions_devoir_id'), table_name='soumissions')
    op.drop_table('soumissions')
    op.drop_index(op.f('ix_supports_pedagogiques_id'), table_name='supports_pedagogiques')
    op.drop_index(op.f('ix_supports_pedagogiques_cours_id'), table_name='supports_pedagogiques')
    op.drop_table('supports_pedagogiques')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_evaluation_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_eleve_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_devoirs_id'), table_name='devoirs')
    op.drop_index(op.f('ix_devoirs_formateur_id'), table_name='devoirs')
    op.drop_index(op.f('ix_devoirs_cours_id'), table_name='devoirs')
    op.drop_index(op.f('ix_devoirs_classe_id'), table_name='devoirs')
    op.drop_table('devoirs')
    op.drop_table('parent_eleve')
    op.drop_index(op.f('ix_inscriptions_id'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_eleve_id'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_classe_id'), table_name='inscriptions')
    op.drop_index(op.f('ix_inscriptions_annee_scolaire_id'), table_name='inscriptions')
    op.drop_table('inscriptions')
    op.drop_index(op.f('ix_evaluations_matiere_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_classe_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_annee_scolaire_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_emplois_du_temps_matiere_id'), table_name='emplois_du_temps')
    op.drop_index(op.f('ix_emplois_du_temps_id'), table_name='emplois_du_temps')
    op.drop_index(op.f('ix_emplois_du_temps_formateur_id'), table_name='emplois_du_temps')
    op.drop_index(op.f('ix_emplois_du_temps_classe_id'), table_name='emplois_du_temps')
    op.drop_index(op.f('ix_emplois_du_temps_annee_scolaire_id'), table_name='emplois_du_temps')
    op.drop_table('emplois_du_temps')
    op.drop_index(op.f('ix_cours_matiere_id'), table_name='cours')
    op.drop_index(op.f('ix_cours_id'), table_name='cours')
    op.drop_index(op.f('ix_cours_formateur_id'), table_name='cours')
    op.drop_index(op.f('ix_cours_classe_id'), table_name='cours')
    op.drop_table('cours')
    op.drop_index(op.f('ix_absences_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_formateur_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_eleve_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_classe_id'), table_name='absences')
    op.drop_index(op.f('ix_absences_annee_scolaire_id'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_responsables_pedagogiques_user_id'), table_name='responsables_pedagogiques')
    op.drop_index(op.f('ix_responsables_pedagogiques_id'), table_name='responsables_pedagogiques')
    op.drop_table('responsables_pedagogiques')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_annonces_id'), table_name='annonces')
    op.drop_index(op.f('ix_annonces_auteur_id'), table_name='annonces')
    op.drop_table('annonces')
    # ### end Alembic commands ###
