"""Fix Utilisateur-AnneeScolaire relation

Revision ID: 8090c8818672
Revises: 97d8ed0aff8b
Create Date: 2026-03-10 16:05:50.845841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8090c8818672'
down_revision: Union[str, Sequence[str], None] = '97d8ed0aff8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
