"""initial migration

Revision ID: 97d8ed0aff8b
Revises: 
Create Date: 2026-03-10 16:00:46.696443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d8ed0aff8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annee_scolaires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annee_scolaires_id'), 'annee_scolaires', ['id'], unique=False)
    op.create_index(op.f('ix_annee_scolaires_name'), 'annee_scolaires', ['name'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_table('matieres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matieres_id'), 'matieres', ['id'], unique=False)
    op.create_index(op.f('ix_matieres_name'), 'matieres', ['name'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('scholar_year_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['scholar_year_id'], ['annee_scolaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_firstname'), 'utilisateurs', ['firstname'], unique=False)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_name'), 'utilisateurs', ['name'], unique=False)
    op.create_index(op.f('ix_utilisateurs_scholar_year_id'), 'utilisateurs', ['scholar_year_id'], unique=False)
    op.create_table('administrateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrateurs_id'), 'administrateurs', ['id'], unique=False)
    op.create_index(op.f('ix_administrateurs_user_id'), 'administrateurs', ['user_id'], unique=False)
    op.create_table('directeurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directeurs_id'), 'directeurs', ['id'], unique=False)
    op.create_index(op.f('ix_directeurs_user_id'), 'directeurs', ['user_id'], unique=False)
    op.create_table('eleves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eleves_class_id'), 'eleves', ['class_id'], unique=False)
    op.create_index(op.f('ix_eleves_id'), 'eleves', ['id'], unique=False)
    op.create_index(op.f('ix_eleves_user_id'), 'eleves', ['user_id'], unique=False)
    op.create_table('formateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formateurs_id'), 'formateurs', ['id'], unique=False)
    op.create_index(op.f('ix_formateurs_user_id'), 'formateurs', ['user_id'], unique=False)
    op.create_table('formateur_classe',
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('classe_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.PrimaryKeyConstraint('formateur_id', 'classe_id')
    )
    op.create_table('formateur_matiere',
    sa.Column('formateur_id', sa.UUID(), nullable=False),
    sa.Column('matiere_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['formateur_id'], ['formateurs.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('formateur_id', 'matiere_id')
    )
    op.create_table('parents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['eleves.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_student_id'), 'parents', ['student_id'], unique=False)
    op.create_index(op.f('ix_parents_user_id'), 'parents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parents_user_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_student_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_table('formateur_matiere')
    op.drop_table('formateur_classe')
    op.drop_index(op.f('ix_formateurs_user_id'), table_name='formateurs')
    op.drop_index(op.f('ix_formateurs_id'), table_name='formateurs')
    op.drop_table('formateurs')
    op.drop_index(op.f('ix_eleves_user_id'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_id'), table_name='eleves')
    op.drop_index(op.f('ix_eleves_class_id'), table_name='eleves')
    op.drop_table('eleves')
    op.drop_index(op.f('ix_directeurs_user_id'), table_name='directeurs')
    op.drop_index(op.f('ix_directeurs_id'), table_name='directeurs')
    op.drop_table('directeurs')
    op.drop_index(op.f('ix_administrateurs_user_id'), table_name='administrateurs')
    op.drop_index(op.f('ix_administrateurs_id'), table_name='administrateurs')
    op.drop_table('administrateurs')
    op.drop_index(op.f('ix_utilisateurs_scholar_year_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_name'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_firstname'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_matieres_name'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_id'), table_name='matieres')
    op.drop_table('matieres')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_annee_scolaires_name'), table_name='annee_scolaires')
    op.drop_index(op.f('ix_annee_scolaires_id'), table_name='annee_scolaires')
    op.drop_table('annee_scolaires')
    # ### end Alembic commands ###
